### ISSUE TITLE
Predicting probabilties

### ISSUE THREAD

**Issue by gvyshnya** [dmarcous/CRAN_deepboost#2]
It would be nice to add prediction of class probabilities, in addition to label prediction.  So it would become possible to predict class probabilities like,

pred <- predict(mod6, newdata=test, type="probs")

**Comment by dmarcous** [comment]
completely agree.
I'll try to get to it around August :)

**Comment by gvyshnya** [comment]
Thanks, appreciated!

**Comment by dfalbel** [comment]
Is there any plans for that? Is there anyway I can help with?

**Comment by dmarcous** [comment]
Solved, available in the new version (0.1.6) with predict(...,type="response")
