### ISSUE TITLE
The algorithm does not work after iteration 1?

### ISSUE THREAD

**Issue by wangg12** [dmarcous/CRAN_deepboost#4]
This is the output of one training process. Here the first iteration goes well, while after that strange things happened. 
The dataset is a toy dataset produced by multi-variate normal random
 with `cov=50*I_50` and `mean: ones(1, 50), ones(-1, 50)`.
With `ada` in R, the error can reach about 0.18.

Please help me find out what is going wrong. Thanks.
```
Iteration: 1, error: 0.321375, avg tree size: 63, num trees: 1
Iteration: 2, error: 0.5, avg tree size: nan, num trees: 0
Iteration: 3, error: 0.5, avg tree size: nan, num trees: 0
Iteration: 4, error: 0.5, avg tree size: nan, num trees: 0
Iteration: 5, error: 0.5, avg tree size: nan, num trees: 0
Iteration: 6, error: 0.5, avg tree size: nan, num trees: 0
Iteration: 7, error: 0.5, avg tree size: nan, num trees: 0
Iteration: 8, error: 0.5, avg tree size: nan, num trees: 0
Iteration: 9, error: 0.5, avg tree size: nan, num trees: 0
Iteration: 10, error: 0.5, avg tree size: nan, num trees: 0
```

**Comment by wangg12** [comment]
This problem happens only when the loss type is "exponential". You can reproduce it by setting it in the demo code. Maybe there are problems in the code for 'e'.

**Comment by dmarcous** [comment]
Hi, thanks for the catch! I'll try to look into it as soon as possible.
(Your are welcome to contribute a fix if you find one, I won't get to it before the weekend)

**Comment by wangg12** [comment]
@dmarcous I've fixed this by correcting an error in boost.cc.

**Comment by dmarcous** [comment]
Looks good to me.
Merging to master and updating CRAN.
Thanks @wangg12
